// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBDDIBiSDxuH7YQqGeBWQVZ9NbycoMv0',
    appId: '1:349946200961:web:2c5f2c4562822210589e80',
    messagingSenderId: '349946200961',
    projectId: 'mesozoica-f7ea0',
    authDomain: 'mesozoica-f7ea0.firebaseapp.com',
    storageBucket: 'mesozoica-f7ea0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Ep_lQPuIQeYfc8uHwAXfoPWNJ9e_Q4U',
    appId: '1:349946200961:android:c013fa666f1429c7589e80',
    messagingSenderId: '349946200961',
    projectId: 'mesozoica-f7ea0',
    storageBucket: 'mesozoica-f7ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYM9jOYRF71dUVqWosnQ4xki2_bE7Jqhs',
    appId: '1:349946200961:ios:6c4414a3c59cf365589e80',
    messagingSenderId: '349946200961',
    projectId: 'mesozoica-f7ea0',
    storageBucket: 'mesozoica-f7ea0.firebasestorage.app',
    iosClientId: '349946200961-fduc7bsj1rlsuu9d5jl5mqo8vlmm6tpc.apps.googleusercontent.com',
    iosBundleId: 'com.desiredewaele.mesozoica',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYM9jOYRF71dUVqWosnQ4xki2_bE7Jqhs',
    appId: '1:349946200961:ios:0fd66aec03c014cc589e80',
    messagingSenderId: '349946200961',
    projectId: 'mesozoica-f7ea0',
    storageBucket: 'mesozoica-f7ea0.firebasestorage.app',
    iosClientId: '349946200961-ab0s37sp2mnf0346fnmjcpscf9ittase.apps.googleusercontent.com',
    iosBundleId: 'com.desiredewaele.mesozoica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcBDDIBiSDxuH7YQqGeBWQVZ9NbycoMv0',
    appId: '1:349946200961:web:7d01d3273e45d2ce589e80',
    messagingSenderId: '349946200961',
    projectId: 'mesozoica-f7ea0',
    authDomain: 'mesozoica-f7ea0.firebaseapp.com',
    storageBucket: 'mesozoica-f7ea0.firebasestorage.app',
  );
}
