"""Shared config, models, tokens, errors, and checkpoint primitives."""

from mesozoica_ai.common.batch import (
    DEFAULT_NAMESPACE,
    DEFAULT_SUBJECT_KIND,
    BatchSummary,
    JobSummary,
    snapshot_scope,
    subject_metadata,
    subject_query,
)
from mesozoica_ai.common.checkpoints import (
    acquisition_needed,
    begin_acquisition,
    begin_embedding,
    begin_indexing,
    complete_acquisition,
    complete_embedding,
    complete_indexing,
    embedding_needed,
    fail_acquisition,
    fail_embedding,
    fail_indexing,
    indexing_needed,
    reset_embedding,
    reset_indexing,
)
from mesozoica_ai.common.config import AiConfig
from mesozoica_ai.common.errors import (
    BatchWriteError,
    CitationError,
    ConfigurationError,
    IndexCompatibilityError,
    InsufficientEvidenceError,
    RateLimitedError,
    SourceFetchError,
    StructuredOutputError,
)
from mesozoica_ai.common.inventory import (
    KnowledgeOverview,
    sql_embedded_overview,
    sql_knowledge_overview,
)
from mesozoica_ai.common.metadata import SourceMetadata
from mesozoica_ai.common.models import (
    Chunk,
    CitedOutput,
    Document,
    EmbeddedChunk,
    Evidence,
    EvidencePolicy,
    IndexResult,
    KnowledgeChunk,
    KnowledgeDocument,
    PrepareEmbeddingsResult,
    RetrievalMode,
    RetrievalResult,
    RetrievedChunk,
    SourceDocument,
    SyncResult,
)
from mesozoica_ai.common.persist import acquire_knowledge, needs_acquisition, store_documents
from mesozoica_ai.common.resume import UnitOfWork, run_resumable_item
from mesozoica_ai.common.store import SessionUnitOfWork
from mesozoica_ai.common.tokens import Encoding, TokenCounter, TokenizerError, load_encoding

__all__ = [
    "AiConfig",
    "BatchSummary",
    "BatchWriteError",
    "Chunk",
    "CitationError",
    "CitedOutput",
    "ConfigurationError",
    "DEFAULT_NAMESPACE",
    "DEFAULT_SUBJECT_KIND",
    "Document",
    "EmbeddedChunk",
    "Encoding",
    "Evidence",
    "EvidencePolicy",
    "IndexCompatibilityError",
    "IndexResult",
    "InsufficientEvidenceError",
    "JobSummary",
    "KnowledgeOverview",
    "sql_embedded_overview",
    "sql_knowledge_overview",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "PrepareEmbeddingsResult",
    "RetrievalMode",
    "RetrievalResult",
    "RetrievedChunk",
    "SessionUnitOfWork",
    "SourceDocument",
    "RateLimitedError",
    "SourceFetchError",
    "SourceMetadata",
    "StructuredOutputError",
    "SyncResult",
    "TokenCounter",
    "TokenizerError",
    "UnitOfWork",
    "acquire_knowledge",
    "acquisition_needed",
    "begin_acquisition",
    "begin_embedding",
    "begin_indexing",
    "complete_acquisition",
    "complete_embedding",
    "complete_indexing",
    "embedding_needed",
    "fail_acquisition",
    "fail_embedding",
    "fail_indexing",
    "indexing_needed",
    "load_encoding",
    "needs_acquisition",
    "reset_embedding",
    "reset_indexing",
    "run_resumable_item",
    "snapshot_scope",
    "store_documents",
    "subject_metadata",
    "subject_query",
]
